"""initial schema

Revision ID: 71e184d4d31a
Revises: 
Create Date: 2026-07-09 23:10:16.879707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e184d4d31a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_types',
    sa.Column('aircraft_type', sa.String(), nullable=False),
    sa.Column('max_cargo_weight_kg', sa.Float(), nullable=False),
    sa.Column('max_cargo_volume_m3', sa.Float(), nullable=False),
    sa.Column('temperature_controlled_capacity_kg', sa.Float(), nullable=True),
    sa.Column('is_freighter', sa.Boolean(), nullable=True),
    sa.Column('dangerous_goods_allowed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('aircraft_type')
    )
    op.create_table('airports',
    sa.Column('airport_code', sa.String(), nullable=False),
    sa.Column('airport_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('customs_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('airport_code')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_airport', sa.String(), nullable=False),
    sa.Column('destination_airport', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('route_type', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('customs_required', sa.Boolean(), nullable=True),
    sa.Column('restricted_cargo_allowed', sa.Boolean(), nullable=True),
    sa.Column('embargo_active', sa.Boolean(), nullable=True),
    sa.Column('embargoed_cargo_types', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['destination_airport'], ['airports.airport_code'], ),
    sa.ForeignKeyConstraint(['origin_airport'], ['airports.airport_code'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_type', sa.String(), nullable=False),
    sa.Column('aircraft_registration', sa.String(), nullable=True),
    sa.Column('departure_scheduled', sa.DateTime(), nullable=False),
    sa.Column('arrival_scheduled', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_type'], ['aircraft_types.aircraft_type'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('cargo_requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('requires_temperature_control', sa.Boolean(), nullable=True),
    sa.Column('priority_class', sa.String(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('booking_cutoff_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('optimization_results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_name', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['cargo_requests.request_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_results')
    op.drop_table('cargo_requests')
    op.drop_table('flights')
    op.drop_table('routes')
    op.drop_table('airports')
    op.drop_table('aircraft_types')
    # ### end Alembic commands ###
